export PATH=/opt/local/bin:/opt/local/sbin:${PATH}
export MANPATH=/opt/local/share/man:/opt/local/man:${MANPATH}
export LANG='ja_JP.UTF-8'
export EDITOR=`which vim`
export CVS_EDITOR=${EDITOR}
export SVN_EDITOR=${EDITOR}
export GIT_EDITOR=${EDITOR}
export BZR_EDITOR=${EDITOR}
export HGENCODING='UTF-8'

export CC='gcc'
export CXX='g++'
export LD_LIBRARY_PATH='/opt/local/lib'
